window.SEED_FOODS=[
{name:'Куриная грудка',category:'protein',kcal:165,protein_g:31,fat_g:3.6,carb_g:0,fiber_g:0,sugar_g:0,sodium_mg:74,fiber_type:'none',irritants:[],risk:'low'},
{name:'Индейка (грудка)',category:'protein',kcal:135,protein_g:30,fat_g:1,carb_g:0,fiber_g:0,sugar_g:0,sodium_mg:55,fiber_type:'none',irritants:[],risk:'low'},
{name:'Говядина (нежирная)',category:'protein',kcal:158,protein_g:26,fat_g:6,carb_g:0,fiber_g:0,sugar_g:0,sodium_mg:55,fiber_type:'none',irritants:[],risk:'medium'},
{name:'Треска',category:'protein',kcal:82,protein_g:18,fat_g:0.7,carb_g:0,fiber_g:0,sugar_g:0,sodium_mg:78,fiber_type:'none',irritants:[],risk:'low'},
{name:'Лосось',category:'protein',kcal:208,protein_g:20,fat_g:13,carb_g:0,fiber_g:0,sugar_g:0,sodium_mg:59,fiber_type:'none',irritants:['fat'],risk:'medium'},
{name:'Яйцо куриное',category:'protein',kcal:143,protein_g:13,fat_g:10,carb_g:1.1,fiber_g:0,sugar_g:1.1,sodium_mg:140,fiber_type:'none',irritants:[],risk:'low'},
{name:'Творог 5%',category:'dairy',kcal:121,protein_g:17,fat_g:5,carb_g:1.8,fiber_g:0,sugar_g:1.8,sodium_mg:40,fiber_type:'none',irritants:[],risk:'low'},
{name:'Кефир 1%',category:'dairy',kcal:40,protein_g:3,fat_g:1,carb_g:4,fiber_g:0,sugar_g:4,sodium_mg:50,fiber_type:'none',irritants:[],risk:'low'},
{name:'Йогурт натуральный',category:'dairy',kcal:60,protein_g:3.5,fat_g:2,carb_g:6,fiber_g:0,sugar_g:6,sodium_mg:46,fiber_type:'none',irritants:[],risk:'low'},
{name:'Рис белый (крупа)',category:'carb',kcal:365,protein_g:7,fat_g:0.6,carb_g:79,fiber_g:1.3,sugar_g:0.1,sodium_mg:5,fiber_type:'none',irritants:[],risk:'low'},
{name:'Гречка (крупа)',category:'carb',kcal:343,protein_g:13,fat_g:3.4,carb_g:71,fiber_g:10,sugar_g:0,sodium_mg:1,fiber_type:'mixed',irritants:[],risk:'low'},
{name:'Овсянка (геркулес)',category:'carb',kcal:366,protein_g:12,fat_g:6,carb_g:62,fiber_g:8,sugar_g:1,sodium_mg:6,fiber_type:'soluble',irritants:[],risk:'low'},
{name:'Киноа',category:'carb',kcal:368,protein_g:14,fat_g:6,carb_g:64,fiber_g:7,sugar_g:0,sodium_mg:5,fiber_type:'mixed',irritants:[],risk:'low'},
{name:'Хлеб белый пшеничный',category:'carb',kcal:265,protein_g:9,fat_g:3.2,carb_g:49,fiber_g:2.7,sugar_g:5,sodium_mg:491,fiber_type:'none',irritants:[],risk:'low'},
{name:'Картофель',category:'veg',kcal:77,protein_g:2,fat_g:0.1,carb_g:17,fiber_g:2.2,sugar_g:0.8,sodium_mg:6,fiber_type:'mixed',irritants:[],risk:'low'},
{name:'Морковь',category:'veg',kcal:41,protein_g:0.9,fat_g:0.2,carb_g:10,fiber_g:2.8,sugar_g:4.7,sodium_mg:69,fiber_type:'mixed',irritants:[],risk:'low'},
{name:'Кабачок',category:'veg',kcal:17,protein_g:1.2,fat_g:0.3,carb_g:3.1,fiber_g:1,sugar_g:2.5,sodium_mg:8,fiber_type:'soluble',irritants:[],risk:'low'},
{name:'Брокколи',category:'veg',kcal:34,protein_g:2.8,fat_g:0.4,carb_g:7,fiber_g:2.6,sugar_g:1.7,sodium_mg:33,fiber_type:'insoluble',irritants:['insoluble_fiber'],risk:'medium'},
{name:'Цветная капуста',category:'veg',kcal:25,protein_g:1.9,fat_g:0.3,carb_g:5,fiber_g:2,sugar_g:1.9,sodium_mg:30,fiber_type:'soluble',irritants:[],risk:'low'},
{name:'Тыква',category:'veg',kcal:26,protein_g:1,fat_g:0.1,carb_g:6.5,fiber_g:0.5,sugar_g:2.8,sodium_mg:1,fiber_type:'soluble',irritants:[],risk:'low'},
{name:'Огурец',category:'veg',kcal:15,protein_g:0.7,fat_g:0.1,carb_g:3.6,fiber_g:0.5,sugar_g:1.7,sodium_mg:2,fiber_type:'mixed',irritants:[],risk:'low'},
{name:'Помидор',category:'veg',kcal:18,protein_g:0.9,fat_g:0.2,carb_g:3.9,fiber_g:1.2,sugar_g:2.6,sodium_mg:5,fiber_type:'mixed',irritants:[],risk:'low'},
{name:'Салат айсберг',category:'veg',kcal:14,protein_g:0.9,fat_g:0.1,carb_g:2.9,fiber_g:1.2,sugar_g:0.7,sodium_mg:11,fiber_type:'mixed',irritants:[],risk:'low'},
{name:'Шпинат',category:'veg',kcal:23,protein_g:2.9,fat_g:0.4,carb_g:3.6,fiber_g:2.2,sugar_g:0.4,sodium_mg:79,fiber_type:'mixed',irritants:[],risk:'low'},
{name:'Свёкла',category:'veg',kcal:43,protein_g:1.6,fat_g:0.2,carb_g:9.6,fiber_g:2.8,sugar_g:6.8,sodium_mg:78,fiber_type:'insoluble',irritants:['insoluble_fiber'],risk:'medium'},
{name:'Банан',category:'fruit',kcal:89,protein_g:1.1,fat_g:0.3,carb_g:23,fiber_g:2.6,sugar_g:12,sodium_mg:1,fiber_type:'mixed',irritants:[],risk:'low'},
{name:'Яблоко (без кожуры)',category:'fruit',kcal:48,protein_g:0.4,fat_g:0.3,carb_g:11.4,fiber_g:1.2,sugar_g:10,sodium_mg:1,fiber_type:'mixed',irritants:[],risk:'low'},
{name:'Груша',category:'fruit',kcal:57,protein_g:0.4,fat_g:0.1,carb_g:15,fiber_g:3.1,sugar_g:10,sodium_mg:1,fiber_type:'mixed',irritants:[],risk:'low'},
{name:'Авокадо',category:'fruit',kcal:160,protein_g:2,fat_g:14.7,carb_g:8.5,fiber_g:6.7,sugar_g:0.7,sodium_mg:7,fiber_type:'mixed',irritants:['fat'],risk:'medium'},
{name:'Масло оливковое',category:'fat',kcal:884,protein_g:0,fat_g:100,carb_g:0,fiber_g:0,sugar_g:0,sodium_mg:2,fiber_type:'none',irritants:['fat'],risk:'medium'},
{name:'Масло сливочное',category:'fat',kcal:717,protein_g:0.9,fat_g:81,carb_g:0.1,fiber_g:0,sugar_g:0.1,sodium_mg:11,fiber_type:'none',irritants:['fat'],risk:'high'},
{name:'Масло льняное',category:'fat',kcal:884,protein_g:0,fat_g:100,carb_g:0,fiber_g:0,sugar_g:0,sodium_mg:0,fiber_type:'none',irritants:['fat'],risk:'medium'},
{name:'Грецкий орех',category:'nuts',kcal:654,protein_g:15,fat_g:65,carb_g:14,fiber_g:6.7,sugar_g:2.6,sodium_mg:2,fiber_type:'mixed',irritants:['fat'],risk:'high'},
{name:'Миндаль',category:'nuts',kcal:579,protein_g:21,fat_g:50,carb_g:22,fiber_g:12.5,sugar_g:4.4,sodium_mg:1,fiber_type:'mixed',irritants:['fat'],risk:'high'},
{name:'Чай зелёный',category:'drink',kcal:1,protein_g:0,fat_g:0,carb_g:0,fiber_g:0,sugar_g:0,sodium_mg:1,fiber_type:'none',irritants:['caffeine'],risk:'low'},
{name:'Чай чёрный',category:'drink',kcal:1,protein_g:0,fat_g:0,carb_g:0.3,fiber_g:0,sugar_g:0,sodium_mg:1,fiber_type:'none',irritants:['caffeine'],risk:'low'},
{name:'Вода',category:'drink',kcal:0,protein_g:0,fat_g:0,carb_g:0,fiber_g:0,sugar_g:0,sodium_mg:0,fiber_type:'none',irritants:[],risk:'low'}
];
